server:
  port: 8081

spring:
  profiles:
    active: local

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.ag.channel.model
  configuration.map-underscore-to-camel-case: true


