#mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/duolaimei?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: lubao
    password: 84952139
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

logging:
  level:
#    root: error
    cn.ag.channel.mapper: debug

  file:
    path: D:\ideaLog




