#mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/duolaimei?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 84952139
    driver-class-name: com.mysql.cj.jdbc.Driver

  #当个文件大小   每次请求的大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

uploadFilePath: /duolaimei/picFile
uploadFileExcel: /duolaimei/excelFile

#陆宝 wx518a32176cd9bd91 f7792f1a5ec48aad5f269ad6a3b91057
#多来美公众号密码 Kobe19890814


wxAppId: wxcc9a3440d787c2af
wxAppSecret: 30b75fb442136065c035be4fb215f32a

interceptorLoginPath: http://mxcoffice.cn/duolaimei/login.html

logging:
  level:
    root: error
#    cn.mx.duolaimei.dao: debug

  file:
    path: /duolaimei/logs
